config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get '/articles' => 'articles#index'
  get '/articles/:id' => 'articles#show', as: 'show_article'
  get '/article/new' => 'articles#new', as: 'new_article'
  post '/article/create' => 'articles#create', as: 'create_article'
  get 'articles/edit/:id' => 'articles#edit', as: 'edit_article'
  patch 'articles/update/:id' => 'articles#update', as: 'update_article'
  get 'articles/destroy/:id' => 'articles#destroy', as: 'delete_article'
  
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :desc)
  end
  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new
    @article.title = params[:title]
    @article.content = params[:content]
    if @article.title != "" or @article.content != ""
      if @article.save
        redirect_to articles_path
      else
        render :new
      end
    else
      redirect_to new_article_path
      flash[:alert] = "Can't publish empty article"
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(title: params[:title], content: params[:content])
      flash[:notice] = "Article was updated"
      redirect_to articles_path(@article)
     else
      flash[:alert] = "Article was not updated"
      render 'edit'
     end
  end

  def destroy
    @article = Article.find(params[:id])
  @article.destroy
  flash[:warning] = "Article was deleted"
  redirect_to articles_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :username, :password, :mobile_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="container mx-5">
    
    <%= form_with url: update_article_path(@article), method: "patch" do |f|%>
    
    <p>
        <%= f.label :title %> <br />
        <%= f.text_field :title, :value => @article.title %>
    </p>
    <p>
        <%= f.label :content %> <br />
        <%= f.text_area :content, value: @article.content, size: "100x25", class: "focus:outline-none" %>
    </p>
    <p>
            <%= button_tag(type: 'submit', class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mt-5") do %>
    Edit
    <% end %>
    </p>
    
    <%= link_to :back do %>
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold my-1 py-2 px-4 rounded">Back</button>
    <% end %>
    <%= link_to articles_path do %>
    <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold my-1 py-2 px-4 rounded">Home</button>
    <% end %>
    <% end %>
</div>

app/views/articles/index.html.erb
<h1 class= "font-bold text-xl mb-2 mx-5"> WELLO HORLD!</h2>
<p class="text-gray-700 text-base mx-5">Welcome to my blog!</p>

<table class="table-fixed text-left m-4 border-separate border border-green-800">
    <thead>
        <tr>
            <th class="w-1/4 border border-green-800">Title</th>
            <th class="w-1/2 border border-green-800">Content</th>
            <th class="w-1/16 border border-green-800">Edit</th>
            <th class="w-1/16 border border-green-800">Delete</th>
            <th class="w-1/8 border border-green-800">Last Upated</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr max-height="50px" class="overflow-hidden">
                <td class= "border border-green-800 font-bold text-xl"><%=link_to "#{article.title.truncate(20)}" , show_article_path(article) %></td>
                <td class= "border border-green-800 text-gray-700 text-base" ><%= article.content.truncate(50) %></td>
                <td class= "border border-green-800"><%= link_to  edit_article_path(article) do %>
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold my-1 py-2 px-4 rounded">Edit</button>
                    <%end%>
                 </td>
                <td class= "border border-green-800"><%= link_to delete_article_path(article) do %>
                <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</button>
                <%end%>
                </td>
                <td class= "border border-green-800"> <%= article.updated_at %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<div class="flex justify-center"><%= link_to new_article_path do %>
<button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">NEW</button>
<%end%></div>

app/views/articles/new.html.erb
<div class="my-5 mx-5">
<%= form_with url: create_article_path do |f|%>

<p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :content %> <br />
    <%= f.text_area :content, size: "100x25", class: "focus:outline-none" %>
</p>
<p>
    <%= button_tag(type: 'submit', class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mt-5") do %>
 Publish
<% end %>
</p>
<%= link_to :back do %>
<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold my-1 py-2 px-4 rounded">Back</button>
<% end %>
<%= link_to articles_path do %>
    <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold my-1 py-2 px-4 rounded">Home</button>
    <% end %>
<% end %>
</div>

app/views/articles/show.html.erb
<div class="container ">
<div  class="max-w rounded shadow-lg my-5">
    <h1 class="font-bold text-xl mb-2"><%= @article.title %></h1>
    <p class="text-gray-700 text-base"><%= simple_format @article.content.gsub(/(?:\n\r?|\r\n?)/, '<br>') %></p>
</div>
</div>

<div>
    <%= link_to  edit_article_path(@article) do %>
        <button class="bg-green-500 hover:bg-green-700 text-white font-bold my-1 py-2 px-4 rounded">Edit</button>
    <%end%>
    <%= link_to delete_article_path(@article) do %>
        <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</button>
    <%end%>
</div>
<%= link_to :back do %>
<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold my-1 py-2 px-4 rounded">Back</button>
<% end %>
<%= link_to articles_path do %>
    <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold my-1 py-2 px-4 rounded">Home</button>
    <% end %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>blog ni deyb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	  <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
     textarea { 
     resize: none; 
    }
    </style>
  </head>

  <body class="container mx-auto font-sans bg-white bg-opacity-80 min-h-screen pt-5 p-2 rounded-3xl">
        <h1 class='m-6'> BLOG NI DAVE</h1>
  <% flash.each do |type, msg| %>
  <% if type == "alert" %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative">
    <%= msg %>
  </div>
  <% elsif type == "notice" %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" >
    <%= msg %>
  </div>
  <% elsif type == "warning" %>
  <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded relative" >
    <%= msg %>
  </div>
    <% end %>
    <% end %>
      <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.number_field :mobile_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Username</th>
      <th>Password</th>
      <th>Mobile number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.mobile_number %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @user.mobile_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>